---
# unfortunately, ansible doesn't allow looping roles
# so we have a local tasks "create_one" which includes facts & create of the route role
# hence we can create multiple snapshot_policy in a loop

# - debug: var=qtask_child

- name: Create multiple Snapshot Policy
  include_tasks: "create_one.yml" 
  loop_control:
    loop_var: snap_item
    label: "Creating Snapshot Policy {{ snap_item.name }}"
  loop: "{{ snapshot_policy }}"
...