---

## Naming facts
- name: Merge Extravars
  ansible.builtin.set_fact:
    snapshot_policy : "{{ 'snapshot_policy' | netapp_ps.maf.merge_lists(v=vars_local,required_keys=['name'],c=qtask_child) }}"
...