- hosts: localhost
  gather_facts: no
  vars: 
    vars_absolute_path: /home/cbcadmin/vars/
  vars_files:
    - "{{ vars_absolute_path }}/vars.yml"
  tasks:
    # - name: patch bootarg
    #   netapp.ontap.na_ontap_rest_cli:
    #     hostname: "{{ src_cluster.hostname }}"
    #     username: "{{ src_cluster.username }}"
    #     password: "{{ src_cluster.password }}"
    #     validate_certs: no
    #     command: debug/kenv
    #     verb: PATCH
    #     params:
    #       node: trinidad-01
    #     body:
    #       bootarg.login.allowdiag: "True"

    # - name: patch bootarg with command
    #   netapp.ontap.na_ontap_command:
    #     hostname: "{{ src_cluster.hostname }}"
    #     username: "{{ src_cluster.username }}"
    #     password: "{{ src_cluster.password }}"
    #     validate_certs: no
    #     privilege: advanced
    #     command: ['systemshell','-node','*','-command','sudo','kenv','bootarg.login.allowdiag="true"']
    #     #systemshell -node trinidad-01 -command sudo kenv bootarg.login.allowdiag="true"
    


      
  