#########################
# Playbook creates:
#- clone of an svm configuration
#
# (c) Alexey Mikhaylov
# NetApp Professional Services Germany
# alexey.mikhaylov@netapp.com  
#
# DEMO purpose only!
#########################

---
- hosts: localhost
  gather_facts: no
  connection: local
  collections: 
    - netapp_ps.ontap_specials
    - netapp_ps.ontap
    - netapp_ps.maf
  vars: 
    vars_absolute_path: /home/cbcadmin/vars/
    vars_templates:
    vars_overrides:
    vars_local:
    qlogname: "create_svm.test"                    # log file name prefix
    qlogdir:  "{{ vars['playbook_dir'] }}/logs"    # log file directory
  vars_files:
    - "{{ vars_absolute_path }}/vars.yml"
  tasks:
    - name: Set naming facts - Credentials
      ansible.builtin.set_fact:
        ontap_username: "{{ src_cluster.username }}"
        ontap_password: "{{ src_cluster.password }}"
        cluster:
          management_ip: "{{ src_cluster.hostname }}"
      no_log: false
    
    - name: Read data and create SVM
      include_role: 
        name: netapp_ps.ontap_specials.svm_clone
      vars:
        source_cluster:   "{{ src_cluster }}"
        dest_cluster:     "{{ dst_cluster }}"
        api_path_subset:  svm
        new_svm_name:     "{{ dst_cluster.svm }}"
        clone_volumes:    true
        clone_options:
          split_clone: no
          set_export_policy: yes
          clone_vol_type: rw
          vol_guarantee: 'none'
        clone_config:
          - dns
          - route
          - export_policy
          - nfs
          - name_mapping
          - unix_group
          - unix_user
          - iscsi
          #- cifs
          #- cifs_share
        
    
    - debug: var=vars_local
...

# SVM-level configurations:
# - SVM name
# - Language settings
# - Aggregates (names and UUIDs)
# - IPSpace (name and UUID)
# - Security certificates (UUIDs)
# - Snapshot policies (UUIDs)
# - NFS configuration (allowed and enabled status)
# - CIFS configuration (allowed and enabled status)
# - iSCSI configuration (allowed and enabled status)
# - FCP configuration (allowed and enabled status)
# - NDMP configuration (allowed status)

# Data protection and replication settings:
# - SnapMirror relationships (including SnapMirror policy and schedule)
# - SnapVault relationships (including SnapVault policy and schedule)

# Protocols and services:
# - NFS exports
# - CIFS shares
# - iSCSI LUNs and targets
# - FCP LUNs and targets