# here we assemble all the credentials we need
# we flatten them from dicts
# you can rewrite this how you see fit, to grab the credentials
# this is typically step one of the playbook

- name: Validate input credentials
  ansible.builtin.assert:
    that:
      - input_username is defined
      - input_username | length > 0
      - input_password is defined
      - input_password | length > 0
    msg: "Check credentials. Can't continue"
  
- name: Set naming facts - Credentials
  ansible.builtin.set_fact:
    ontap_username: "{{ input_username }}"
    ontap_password: "{{ input_password }}"
  no_log: true

