---
# unfortunately, ansible doesn't allow looping roles
# so we have a local tasks "create_one" which includes facts & create of the unix_group role
# hence we can create multiple unix_group in a loop

# - debug: var=qtask_child

- name: Create multiple unix groups
  include_tasks: "create_one.yml" 
  loop_control:
    loop_var: unix_group_item
    label: "Creating unix group {{ unix_group_item.name }}"
  loop: "{{ unix_group }}"
