---

## Naming facts
- name: Merge Extravars
  ansible.builtin.set_fact:
    name_mapping : "{{ 'name_mapping' | netapp_ps.maf.merge_lists(v=vars_local,required_keys=['direction'],c=qtask_child) }}"

