---
# unfortunately, ansible doesn't allow looping roles
# so we have a local tasks "create_one" which includes facts & create of the Export Plicy role
# hence we can create multiple Export Plicies in a loop

#- debug: var=qtask_child

- name: Create multiple Export Policies
  include_tasks: "create_one.yml" 
  loop_control:
    loop_var: ep_item
    label: "Creating Export Policy {{ ep_item.name }}"
  loop: "{{ export_policy }}"
