- ansible.builtin.include_role: 
    name: "netapp_ps.ontap.{{ config_item }}"
  vars:
    qtask: facts
    qchild: clone_source
- ansible.builtin.include_role: 
    name: "netapp_ps.ontap.{{ config_item }}"
  vars:
    qtask: create
    qchild: clone_source