---
# unfortunately, ansible doesn't allow looping roles
# so we have a local tasks "create_one" which includes facts & create of the unix_user role
# hence we can create multiple unix_user in a loop

# - debug: var=qtask_child

- name: Create multiple unix users
  include_tasks: "create_one.yml" 
  loop_control:
    loop_var: unix_user_item
    label: "Creating unix user {{ unix_user_item.name }}"
  loop: "{{ unix_user }}"
